name: Update Alerts Config

on:
  workflow_dispatch:
    inputs:
      sporting:
        description: "Sporting enabled"
        required: true
        default: "true"

      woker:
        description: "Woker enabled"
        required: true
        default: "true"

      dexter:
        description: "Dexter enabled"
        required: true
        default: "true"

      seven:
        description: "Seven enabled"
        required: true
        default: "true"
     
      dash:
        description: "Dash enabled"
        required: true
        default: "true"
        
      precio_sporting:
        description: "Precio Sporting"
        required: true
        default: "46000"
      
      precio_woker:
        description: "Precio Woker"
        required: true
        default: "51000"
      
      precio_dexter:
        description: "Precio Dexter"
        required: true
        default: "45000"
      
      precio_seven:
        description: "Precio Seven"
        required: true
        default: "40999"
      
      precio_dash:
        description: "Precio Dash"
        required: true
        default: "40999"
      
      onsports:
        description: "OnSports enabled"
        required: true
        default: "true"

permissions:
  contents: write

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update config_alertas.json
        run: |
          cat > config_alertas.json << EOF
          {
            "sporting": ${{ github.event.inputs.sporting }},
            "woker": ${{ github.event.inputs.woker }},
            "dexter": ${{ github.event.inputs.dexter }},
            "seven": ${{ github.event.inputs.seven }},
            "dash": ${{ github.event.inputs.dash }},
            "onsports": ${{ github.event.inputs.onsports }},

            "precio_sporting": ${{ github.event.inputs.precio_sporting }},
            "precio_woker": ${{ github.event.inputs.precio_woker }},
            "precio_dexter": ${{ github.event.inputs.precio_dexter }},
            "precio_seven": ${{ github.event.inputs.precio_seven }},
            "precio_dash": ${{ github.event.inputs.precio_dash }},
            "precio_onsports": ${{ github.event.inputs.precio_onsports }}
            
          }
          EOF

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add config_alertas.json

          git diff --cached --quiet || git commit -m "Update alerts config"

          git pull --rebase origin Sistemas-UCH

          git push origin Sistemas-UCH
